version: "2"

run:
  issues-exit-code: 1
  tests: false

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - nilnil
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    govet:
      disable:
        - shadow
    errcheck:
      check-type-assertions: false
      check-blank: false

formatters:
  exclusions:
    generated: lax
